spring:
  datasource:
    url: jdbc:mysql://localhost:3306/enrollment1?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: "YOUR_USERNAME"
    password: "YOUR_PASSWORD"
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect

